/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Carlos
 */
public class Busqueda_manual extends javax.swing.JFrame {

    /**
     * Creates new form Busqueda_manual
     */
    public Busqueda_manual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busqueda_manual = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        cargar_info = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultados_posi = new javax.swing.JTextArea();
        Enviar_correos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        busqueda_manual.setText("Busqueda manual ");

        salir.setForeground(new java.awt.Color(255, 0, 0));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        cargar_info.setText("Cargar Informacion");
        cargar_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar_infoActionPerformed(evt);
            }
        });

        resultados_posi.setColumns(20);
        resultados_posi.setRows(5);
        jScrollPane1.setViewportView(resultados_posi);

        Enviar_correos.setText("Enviar Correos");
        Enviar_correos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enviar_correosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(busqueda_manual))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Enviar_correos)
                                .addGap(18, 18, 18)
                                .addComponent(cargar_info)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(atras)
                                .addGap(44, 44, 44)
                                .addComponent(salir)
                                .addGap(9, 9, 9))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(busqueda_manual)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir)
                    .addComponent(atras)
                    .addComponent(cargar_info)
                    .addComponent(Enviar_correos))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        Buscador busc = new Buscador();
        busc.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void cargar_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar_infoActionPerformed
        try {
            System.out.println(resultado());
            resultados_posi.setText(resultado());

        } catch (Exception e) {
            System.out.println("Problema al imprimir datos" + e);
        }
    }//GEN-LAST:event_cargar_infoActionPerformed

    private void Enviar_correosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enviar_correosActionPerformed
        Buscador.Global.eleccion_para_switch = "con_email";// por alguna razon no le da la gana de funcionar 
        Correo C = new Correo();
        C.conexion();
        C.iniciarSesion();  
    }//GEN-LAST:event_Enviar_correosActionPerformed

    public String eleccion() {
        return Buscador.Global.eleccion_para_switch;
    }

//recive la cadena con los resultados
    public String resultado() throws ClassNotFoundException {
        Base_de_datos BD = new Base_de_datos();
        return BD.dat();
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar_correos;
    private javax.swing.JButton atras;
    private javax.swing.JLabel busqueda_manual;
    private javax.swing.JButton cargar_info;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultados_posi;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
